name: PRB

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Dependencies
      - name: Set up dependencies (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          chmod +x ./scripts/macos/install-dependencies.sh
          ./scripts/macos/install-dependencies.sh

      - name: Set up dependencies (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          chmod +x ./scripts/linux/install_dependencies.sh
          ./scripts/linux/install_dependencies.sh

      # Build
      - name: Build (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          make clean
          make macos

      - name: Build (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          make clean
          make linux