name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha'
    branches:
      - macos-automated-release

jobs:
  build-and-release:
    name: Build and Release
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest]
        os: [ macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Dependencies
      - name: Set up dependencies (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          attempts=0
          max_attempts=3
          while [ $attempts -lt $max_attempts ]; do
            brew update && brew upgrade
            if [ $? -eq 0 ]; then
              break
            fi
            echo "Homebrew install failed. Retrying in 5 seconds..."
            sleep 5
            attempts=$((attempts+1))
          done
          if [ $attempts -eq $max_attempts ]; then
            echo "Homebrew install failed after multiple retries."
            exit 1
          fi
          brew install sfml
          brew install nlohmann-json

      - name: Set up dependencies (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libsfml-dev libnlohmann-json-dev
      

      # Build
      - name: Build (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          make clean && make macos

      - name: Build (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          echo "Not implemented yet"
      

      # Package
      - name: Package .app (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          app_name="YARN"
          mkdir -p release/macos
          zip -r release/macos/${app_name}-${{ github.ref_name }}.zip "${app_name}.app"

      - name: Package binary (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          mkdir -p release/linux
          cp build/YARN release/linux/YARN
          tar czvf release/linux.tar.gz -C release/linux .
      

      # Release
      - name: Debug - List release directory
        run: |
          echo "Current working directory: $(pwd)"
          ls -al
          echo "Printing /release"
          ls -al release
          echo "Printing /release/macos"
          ls -al release/macos

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/linux/*.tar.gz
            release/macos/*.zip
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
