name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha'
      - 'v[0-9]+.[0-9]+.[0-9]+-debug'

jobs:
  build-and-release:
    name: Build and Release
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-24.04-arm]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Dependencies
      - name: Set up dependencies (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          chmod +x ./scripts/install-requirements-macos.sh
          ./scripts/install-requirements-macos.sh

      - name: Set up dependencies (Linux x86_64)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          chmod +x ./scripts/ubuntu/install_dependencies.sh
          ./scripts/ubuntu/install_dependencies.sh x86_64
      - name: Set up dependencies (Linux aarch64/arm64)
        if: ${{ matrix.os == 'ubuntu-24.04-arm' }}
        run: |
          chmod +x ./scripts/ubuntu/install_dependencies.sh
          ./scripts/ubuntu/install_dependencies.sh aarch64

      # Build
      - name: Build (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          make clean && make macos

      - name: Build (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm' }}
        run: |
          make clean
          make linux
      

      # Package
      - name: Package .app (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          app_name="YARN"
          echo "Removing quarentine flag for: ${app_name}.app:"
          xattr -cr "${app_name}.app"
          mkdir -p release/macos
          echo "Zip: ${app_name}.app -> release/macos/${app_name}-${{ github.ref_name }}.zip:"
          zip -r release/macos/${app_name}-${{ github.ref_name }}_macos.zip "${app_name}.app"
          echo "Removing quarentine flag for: release/macos/${app_name}-${{ github.ref_name }}_macos.zip:"
          xattr -cr "release/macos/${app_name}-${{ github.ref_name }}_macos.zip"

      - name: Package binary (Linux x86_64)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          mkdir -p release/linux
          chmod +x ./scripts/ubuntu/package.sh
          ./scripts/ubuntu/package.sh x86_64
          mv Y.A.R.N.-x86_64.AppImage release/linux/
          sleep 10
          tar -czvf "release/linux/${app_name}-${GITHUB_REF_NAME}-lnx-x86_64.tar.gz" \
          --warning=no-file-changed \
          -C release/linux Y.A.R.N.-x86_64.AppImage
      - name: Package binary (Linux aarch64/arm64)
        if: ${{ matrix.os == 'ubuntu-24.04-arm' }}
        run: |
          mkdir -p release/linux
          chmod +x ./scripts/ubuntu/package.sh
          ./scripts/ubuntu/package.sh aarch64
          mv Y.A.R.N.-aarch64.AppImage release/linux/
          sleep 10
          tar -czvf "release/linux/${app_name}-${GITHUB_REF_NAME}-lnx-aarch64.tar.gz" \
          --warning=no-file-changed \
          -C release/linux Y.A.R.N.-aarch64.AppImage


      # Release with attached files
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/linux/*.tar.gz
            release/macos/*.zip
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
